---
title: "Projeto exploratória"
author: "Maria Luiza Moura"
date: "2023-12-01"
output: html_document
---

```{r, echo=FALSE}
library(readr)
Banco_de_dados <- read_csv("exploratória/Billionaires Statistics Dataset.csv")
Banco_de_dados <- Banco_de_dados %>%
  mutate(finalWorth = finalWorth/1000)

genero <- Banco_de_dados$gender
patrimonio_bilhoes <- Banco_de_dados$finalWorth
```

```{r, echo=FALSE}
library(dplyr)
contagem_genero <- count(Banco_de_dados, gender)
contagem_genero
```

```{r, echo=FALSE}
library(tidyverse)
Objeto_analise <- ggplot(Banco_de_dados, aes(x = genero, y = patrimonio_bilhoes, color = gender)) + geom_boxplot() + scale_y_continuous(trans = "log10") + labs(title = " Boxplot: Gênero vs. patrimônio total em bilhões de dólares", x = "Gênero", y = "Patrimônios em bilhões")
Objeto_analise
```


```{r}
modelo <- lm(patrimonio_bilhoes ~ genero)
resumo_modelo <- summary(modelo)
r_squared <- resumo_modelo$r.squared
cat("O valor de R² é:", r_squared, "\n")
```


```{r, echo=FALSE}
library(kableExtra)

tabela_resumo <- Banco_de_dados %>%
  group_by(gender) %>%
  summarize(n=n(), Media = mean(finalWorth), S = sd(finalWorth), Mediana = median(finalWorth), Min = min(finalWorth), Max = max(finalWorth), Outliers = count_outliers(finalWorth/n)) %>%
  mutate(
    Genero = gender,
    Media = round(Media, 2),
    S = round(S, 2),
    Outliers = round(Outliers, 3)) %>%
select(Genero, Media, Mediana, S, Min, Max, Outliers, n) %>%
  arrange(desc(Outliers))
  
kable(tabela_resumo, format = "latex", caption = "Medidas do patrimônio total em Bilhões") %>%
  Kable_styling(latex_options = c("striped", "hold_position"), repeat_header_text = TRUE) %>%
  column_spec(4, width = "1cm")%>%
  column_spec(8, width = "1cm")%>%
  column_spec(2, width = "1cm")
```
